config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :leads
  root "leads#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :authenticate_user!

  CLOSE_API_KEY = ENV["CLOSE_API_KEY"]

  def index
    @current_smart_view_id = params[:smart_view_id] || current_user.smart_view_ids&.first
    @smart_views = fetch_smart_views.select { |smart_view| current_user.smart_view_ids.include?(smart_view["id"]) }
    @leads = fetch_leads_by_smartview(@current_smart_view_id)
    @lead_statuses = fetch_lead_statuses
  end

  def update
    response = conn.put(
      "lead/#{params[:id]}/",
      { description: params[:description], status_id: params[:status_id] }.to_json,
      'Content-Type' => 'application/json'
    )

    if response.success?
      render json: { status: 'ok' }
    else
      Rails.logger.error "Close API Error: #{response.status} - #{response.body}"
      render json: { status: 'error', message: response.body }, status: :unprocessable_entity
    end
  end

  private

  def fetch_leads_by_smartview(smart_view_id)
    return [] unless smart_view_id.present?

    search_query = {
      query: {
        type: 'and',
        queries: [
          { type: 'object_type', object_type: 'lead' },
          { type: 'any_of_saved_search', saved_search_ids: [smart_view_id] }
        ]
      },
      _fields: {
        lead: [
          'id', 'name', 'status_label', 'status_id', 'description',
          'contacts', 'custom.cf_K3ausfM3pWXa7CAMQIpWV0eV7Dqc2IXIuOpiX4Luqa9', 'date_created'
        ]
      },
      _limit: 200
    }

    response = conn.post('data/search/', search_query.to_json, 'Content-Type' => 'application/json')
    if response.success?
      JSON.parse(response.body)['data']
    else
      Rails.logger.error "Close API Error: #{response.status} - #{response.body}"
      []
    end
  end

  def fetch_lead_statuses
    response = conn.get('status/lead/')

    if response.success?
      JSON.parse(response.body)['data']
    else
      Rails.logger.error "Close API Error (statuses): #{response.status} - #{response.body}"
      []
    end
  end

  def fetch_smart_views
    response = conn.get("saved_search/")

    if response.success?
      JSON.parse(response.body)["data"]
    else
      Rails.logger.error "Close API Error (statuses): #{response.status} - #{response.body}"
      []
    end
  end

  def conn
    Faraday.new(url: 'https://api.close.com/api/v1/') do |faraday|
      faraday.request :authorization, :basic, CLOSE_API_KEY, ''
      faraday.adapter Faraday.default_adapter
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="sidebar-wrapper active">
    <div class="sidebar-header position-relative">
      <div class="d-flex justify-content-between align-items-center">
        <div class="logo">
          <%= link_to "Close Leads", root_path %>
        </div>
      </div>
    </div>
    
    <div class="sidebar-menu">
      <% if user_signed_in? %>
        <ul class="menu">
          <% if @smart_views %>
            <li class="sidebar-title">Smart Views</li>
            <% @smart_views.each do |smart_view| %>
              <li class="sidebar-item <%= smart_view["id"] == @current_smart_view_id ? "active" : "" %>">
                <%= link_to "/?smart_view_id=#{smart_view["id"]}", data: { turbo: false}, class: "sidebar-link" do %>
                  <span><%= smart_view["name"] %></span>
                <% end %>
              </li>
            <% end %>
          <% end %>
          <li class="sidebar-title">Settings</li>
          <li class="sidebar-item">
            <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "sidebar-link" do %>
                <i class="bi bi-box-arrow-right"></i>
                <span>Logout</span>
            <% end %>
          </li>
        </ul>
        <% else %>
          <ul class="menu">
            <li class="sidebar-item active">
              <%= link_to new_user_session_path, class: "sidebar-link" do %>
                <i class="bi bi-box-arrow-in-right"></i>
                <span>Login</span>
              <% end %>
            </li>
          </ul>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Close Leads App" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_importmap_tags %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "dataTables.bootstrap5.min.css", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "table-datatable-jquery.css", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "app.css", "data-turbo-track": "reload" %>
</head>

<body>
  <div id="app">
    <%= render "layouts/sidebar" %>
    <div id="main">
      <%= yield %>
    </div>
  </div>

  <%= javascript_include_tag "jquery.min.js" %>
  <%= javascript_include_tag "jquery.dataTables.min.js" %>
  <%= javascript_include_tag "dataTables.bootstrap5.min.js" %>
  <%= javascript_include_tag "app.js" %>
</body>
</html>

app/views/leads/index.html.erb
<header class="mb-3">
  <a href="#" class="burger-btn d-block d-xl-none">
    <i class="bi bi-justify fs-3"></i>
  </a>
</header>


<%# Forms outside table connected to rows with form attribute %>
<% @leads.each do |lead| %>
  <%= form_with url: lead_path(lead['id']), id: lead['id'], method: :patch do |form| %>
  <% end %>
<% end %>

<div class="page-heading">
  <div class="page-title">
    <h3>Leads</h3>
  </div>
</div>
<div class="page-content">
  <section class="section">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table" id="leadsTable">
            <thead>
              <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Contacts</th>
                <th>Created</th>
                <th>Kunde</th>
                <% if current_user.admin? %>
                <th>Close.com</th>
                <% end %>
                <th>Description</th>
                <th>Save</th>
              </tr>
            </thead>
            <tbody>
              <% @leads.each do |lead| %>
                <tr>
                  <td><%= lead['name'] %></td>
                  <td data-order="<%= lead['status_label'] %>" data-search="<%= lead['status_label'] %>">
                    <select form=<%= lead['id'] %> name="status_id" class="form-select mb-2">
                      <% @lead_statuses.each do |status| %>
                        <option value="<%= status['id'] %>" <%= "selected" if lead['status_id'] == status['id'] %>>
                          <%= status['label'] %>
                        </option>
                      <% end %>
                    </select>
                  </td>
                  <td>
                    <% if lead['contacts'] %>
                      <% lead['contacts'].each do |contact| %>
                        <% if contact['urls'] && !contact['urls'].empty? %>
                          <% contact['urls'].each do |link| %>
                            <a href="<%= link['url'] %>" target="_blank"><%= contact['name'] %></a><br>
                          <% end %>
                        <% else %>
                          <%= contact['name'] %><br>
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                  <td><%= DateTime.parse(lead['date_created']).strftime('%Y-%m-%d') %></td>
                  <td><%= lead['custom.cf_K3ausfM3pWXa7CAMQIpWV0eV7Dqc2IXIuOpiX4Luqa9'] %></td>
                <% if current_user.admin? %>

                  <td><a href="https://app.close.com/lead/<%= lead['id'] %>" target="_blank">Close.com</a></td>
                  <% end %>

                  <td>
                    <textarea form=<%= lead['id'] %> class="form-control mb-2 auto-resize" name="description" rows="1" cols="20"><%= lead['description'] %></textarea>
                  </td>
                  <td><button form=<%= lead['id'] %> type="submit" class="btn btn-primary">Save</button></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <div>
  </section>
</div>

<!-- Skript zur Initialisierung der DataTable -->
<script>
  document.addEventListener('DOMContentLoaded', () => {  
    let table = new DataTable("#leadsTable", {
      responsive: true,
      // Weitere Optionen nach Bedarf hinzufügen
    });


    // Auto resize description field
    var textareas = document.querySelectorAll('.auto-resize');
    textareas.forEach(function(textarea) {
      // Set initial height
      textarea.style.height = 'auto';
      textarea.style.height = textarea.scrollHeight + 2 + 'px';

      // Add input event listener
      textarea.addEventListener('input', function() {
        this.style.height = 'auto';
        this.style.height = this.scrollHeight + 2 + 'px';
      });
    });
  })
</script>